/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jpinzon.tree;

public class App {

    public static void main(String[] args) {
        BinaryTree<Integer> tree= new BinaryTree<>();
        tree.insert(10);
        tree.insert(15);
        tree.insert(4);
        tree.insert(1);
        tree.insert(3);;
        tree.insert(6);
        System.out.println(tree.toString());
        tree.delete(1);
        System.out.println(tree.toString());
    }
}
